title: Nazim Lachter
description: >
  Nazim Lachter : développeur spécialisé dans la recherche et la réalisation d’idées originales.
  Retrouvez ici mes références ainsi que mes réalisations.

permalink: /posts/:categories/:title

google_analytics: UA-31851675-4

repository: n4zim/n4zim.github.io

disqus:
  shortcode:

markdown: kramdown

pligins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
